# Generated by Django 4.0.3 on 2022-06-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=250)),
                ('recruiter', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='postings/%Y/%m/%d/')),
                ('description', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('pay_range', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=1000)),
                ('num_applicants', models.IntegerField()),
            ],
        ),
    ]
