# Generated by Django 4.0.3 on 2022-06-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='image',
            field=models.ImageField(null=True, upload_to='postings/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='num_applicants',
            field=models.IntegerField(default=1),
        ),
    ]
