# Generated by Django 4.0.3 on 2022-06-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_alter_posting_image_alter_posting_num_applicants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='num_applicants',
            field=models.IntegerField(default=0),
        ),
    ]
