# Generated by Django 4.0.5 on 2022-07-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv_template',
            name='credit',
            field=models.CharField(default='No Credit', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv_template',
            name='numberOfUses',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv_template',
            name='required_data',
            field=models.TextField(default="['Name', 'WorkExp1']"),
            preserve_default=False,
        ),
    ]
