# Generated by Django 4.0.5 on 2022-07-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_map_name', models.CharField(max_length=250)),
                ('nested_nodes', models.PositiveIntegerField(default=0)),
                ('finished_node', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Career',
        ),
    ]
