# Generated by Django 4.0.5 on 2022-07-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_roadmap_delete_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='node_name',
            field=models.CharField(default='xD', max_length=250),
            preserve_default=False,
        ),
    ]
