# Generated by Django 4.0.3 on 2022-06-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ITUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('userType', models.CharField(choices=[('V', 'VISTOR'), ('A', 'ADMIN'), ('S', 'STUDENT'), ('R', 'RECRUITER')], default='V', max_length=256)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('birthdate', models.DateTimeField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('undergraduate_year', models.IntegerField(blank=True, null=True)),
                ('university', models.TextField(blank=True, null=True)),
                ('languages', models.TextField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('other_website_links', models.TextField(blank=True, null=True)),
                ('contact_links', models.TextField(blank=True, null=True)),
                ('is_company', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
