# Generated by Django 4.0.5 on 2022-07-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAL', '0002_alter_ituser_options_alter_ituser_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ituser',
            old_name='firstname',
            new_name='Firstname',
        ),
        migrations.RenameField(
            model_name='ituser',
            old_name='lastname',
            new_name='Lastname',
        ),
        migrations.AddField(
            model_name='ituser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
