# Generated by Django 4.0.5 on 2022-07-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RAL', '0003_rename_firstname_ituser_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ituser',
            old_name='Firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='ituser',
            old_name='Lastname',
            new_name='lastname',
        ),
    ]
