# Generated by Django 4.0.5 on 2022-07-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAL', '0004_rename_firstname_ituser_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ituser',
            name='email',
            field=models.EmailField(max_length=250, unique=True),
        ),
    ]
